/*
 * 
 * Copyright (C) 2011 Pär Crusefalk (SM0RWO)
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 */

/*
 * FrequencyHelper.java
 *
 * Created on 2011-okt-04, 11:02:45
 */

package javapskmail;

/**
 *
 * @author per
 */
public class FrequencyHelper extends javax.swing.JDialog {

    /** Creates new form FrequencyHelper */
    public FrequencyHelper(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        grpSideBand = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        cboServerfq = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cboCenterLF = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        radUSB = new javax.swing.JRadioButton();
        radLSB = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        lblDialFq = new javax.swing.JLabel();
        bClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("javapskmail/Bundle"); // NOI18N
        jLabel1.setText(bundle.getString("FrequencyHelper.jLabel1.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(31, 28, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        cboServerfq.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "3541.5", "3589", "3594", "7042", "7104", "7193", "10147", "10148", "10148.5", "14104", "14107", "14111", "18106", "18108", "21106", "21108", "24928", "28104" }));
        cboServerfq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboServerfqActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 31;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(31, 18, 0, 19);
        getContentPane().add(cboServerfq, gridBagConstraints);

        jLabel2.setText(bundle.getString("FrequencyHelper.jLabel2.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 28, 0, 0);
        getContentPane().add(jLabel2, gridBagConstraints);

        cboCenterLF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "500", "600", "700", "800", "900", "1000", "1100", "1200", "1300", "1400", "1500", "1600", "1700", "1800", "1900", "2000" }));
        cboCenterLF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCenterLFActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 56;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 0, 19);
        getContentPane().add(cboCenterLF, gridBagConstraints);

        jLabel3.setText(bundle.getString("FrequencyHelper.jLabel3.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 28, 0, 0);
        getContentPane().add(jLabel3, gridBagConstraints);

        grpSideBand.add(radUSB);
        radUSB.setSelected(true);
        radUSB.setText(bundle.getString("FrequencyHelper.radUSB.text")); // NOI18N
        radUSB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radUSBActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 0, 0);
        getContentPane().add(radUSB, gridBagConstraints);

        grpSideBand.add(radLSB);
        radLSB.setText(bundle.getString("FrequencyHelper.radLSB.text")); // NOI18N
        radLSB.setToolTipText(bundle.getString("FrequencyHelper.radLSB.toolTipText")); // NOI18N
        radLSB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radLSBActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 0, 0);
        getContentPane().add(radLSB, gridBagConstraints);

        jLabel4.setText(bundle.getString("FrequencyHelper.jLabel4.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 28, 0, 0);
        getContentPane().add(jLabel4, gridBagConstraints);

        lblDialFq.setFont(new java.awt.Font("Ubuntu", 1, 15));
        lblDialFq.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDialFq.setText(bundle.getString("FrequencyHelper.lblDialFq.text")); // NOI18N
        lblDialFq.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblDialFq.setMaximumSize(new java.awt.Dimension(156, 122));
        lblDialFq.setPreferredSize(new java.awt.Dimension(56, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 72;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 0, 19);
        getContentPane().add(lblDialFq, gridBagConstraints);

        bClose.setText(bundle.getString("FrequencyHelper.bClose.text")); // NOI18N
        bClose.setMaximumSize(new java.awt.Dimension(91, 30));
        bClose.setPreferredSize(new java.awt.Dimension(71, 30));
        bClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCloseActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 8, 12, 19);
        getContentPane().add(bClose, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboServerfqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboServerfqActionPerformed
        // Update the dial fq
        Calculatedial();
    }//GEN-LAST:event_cboServerfqActionPerformed

    private void cboCenterLFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCenterLFActionPerformed
        // TODO add your handling code here:
        Calculatedial();
    }//GEN-LAST:event_cboCenterLFActionPerformed

    private void radUSBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radUSBActionPerformed
        // TODO add your handling code here:
        Calculatedial();
    }//GEN-LAST:event_radUSBActionPerformed

    private void radLSBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radLSBActionPerformed
        // TODO add your handling code here:
        Calculatedial();
    }//GEN-LAST:event_radLSBActionPerformed

    private void bCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCloseActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_bCloseActionPerformed

    /**
     * Here is the method that calculates the dial fq
     */
    public void Calculatedial(){
        Float Serverfq;
        Float Audiofq;
        Float Dialfq;
        Serverfq = Float.parseFloat(this.cboServerfq.getSelectedItem().toString());
        Audiofq = Float.parseFloat(this.cboCenterLF.getSelectedItem().toString());
        if (this.radUSB.isSelected()){
            Dialfq = Serverfq-(Audiofq/1000);
        }
        else
        {
            Dialfq = Serverfq+(Audiofq/1000);
        }
        this.lblDialFq.setText(Dialfq.toString());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bClose;
    private javax.swing.JComboBox cboCenterLF;
    private javax.swing.JComboBox cboServerfq;
    private javax.swing.ButtonGroup grpSideBand;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblDialFq;
    private javax.swing.JRadioButton radLSB;
    private javax.swing.JRadioButton radUSB;
    // End of variables declaration//GEN-END:variables

}
