/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * telnetJDialog.java
 *
 * Created on Feb 5, 2010, 4:46:55 PM
 */

package javapskmail;

/**
 *
 * @author rein
 */
public class telnetJDialog extends javax.swing.JDialog {

    static String telnethostTxt;
    static String telnetportTxt;
    static String telnetuseridTxt;
    static String telnetpasswdTxt;
    static String telnetcmd;
    static arq myarq;

    /** Creates new form telnetJDialog */
    public telnetJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        myarq = new arq();
        telnethost.setText(Main.telnethost);
        telnetport.setText(Main.telnetport);
        telnetuserid.setText(Main.userid);
        telnetpasswd.setText(Main.pass);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        telnethost = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        telnetport = new javax.swing.JTextField();
        telnetuserid = new javax.swing.JTextField();
        telnetpasswd = new javax.swing.JTextField();
        telnetOKbutton = new javax.swing.JButton();
        telnetCancelbutton = new javax.swing.JButton();
        telnetConnectbutton = new javax.swing.JButton();
        telnetQuitbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Telnet agent");
        setLocationByPlatform(true);

        jPanel1.setMinimumSize(new java.awt.Dimension(50, 50));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("host");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(jLabel1, gridBagConstraints);

        telnethost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telnethostActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 3);
        jPanel1.add(telnethost, gridBagConstraints);

        jLabel2.setText("port");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setText("userid");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(jLabel3, gridBagConstraints);

        jLabel4.setText("password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(jLabel4, gridBagConstraints);

        telnetport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telnetportActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 0, 3);
        jPanel1.add(telnetport, gridBagConstraints);

        telnetuserid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telnetuseridActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 0, 3);
        jPanel1.add(telnetuserid, gridBagConstraints);

        telnetpasswd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telnetpasswdActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel1.add(telnetpasswd, gridBagConstraints);

        telnetOKbutton.setText("OK");
        telnetOKbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telnetOKbuttonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(telnetOKbutton, gridBagConstraints);

        telnetCancelbutton.setText("Cancel");
        telnetCancelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telnetCancelbuttonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(telnetCancelbutton, gridBagConstraints);

        telnetConnectbutton.setText("Connect");
        telnetConnectbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telnetConnectbuttonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 2);
        jPanel1.add(telnetConnectbutton, gridBagConstraints);

        telnetQuitbutton.setText("Quit");
        telnetQuitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telnetQuitbuttonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 3);
        jPanel1.add(telnetQuitbutton, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void telnethostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telnethostActionPerformed
        // TODO add your handling code here:
        telnethostTxt = telnethost.getText();
    }//GEN-LAST:event_telnethostActionPerformed

    private void telnetportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telnetportActionPerformed
        // TODO add your handling code here:
        telnetportTxt = telnetport.getText();
    }//GEN-LAST:event_telnetportActionPerformed

    private void telnetuseridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telnetuseridActionPerformed
        // TODO add your handling code here:
        telnetuseridTxt = telnetuserid.getText();
    }//GEN-LAST:event_telnetuseridActionPerformed

    private void telnetpasswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telnetpasswdActionPerformed
        // TODO add your handling code here:
        telnetpasswdTxt = telnetpasswd.getText();
    }//GEN-LAST:event_telnetpasswdActionPerformed

    private void telnetOKbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telnetOKbuttonActionPerformed
        // TODO add your handling code here:
        Main.telnethost = telnethost.getText()    ;
        Main.telnetport = telnetport.getText();
        Main.userid = telnetuserid.getText();
        Main.pass = telnetpasswd.getText();
    }//GEN-LAST:event_telnetOKbuttonActionPerformed

    private void telnetCancelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telnetCancelbuttonActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
    }//GEN-LAST:event_telnetCancelbuttonActionPerformed

    private void telnetConnectbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telnetConnectbuttonActionPerformed
        // TODO add your handling code here:
       if (Main.Connected) {
            Main.TX_Text +=  "~TELNET " + telnethost.getText() + " " + telnetport.getText() + "\n";
            if (!telnetuserid.getText().equals("")){
                Main.TX_Text += telnetuserid.getText() + "\n";
            }
            if (!telnetpasswd.getText().equals("")){
                Main.TX_Text += "~PASSx" + wordconv.getps(telnetpasswd.getText()) + "\n";
            }

            myarq.Message("Calling " + telnethost.getText() + "...", 5);
        } else {
            myarq.Message("You need to connect first...", 5);
        }
        Main.telnethost = telnethost.getText()    ;
        Main.telnetport = telnetport.getText();
        Main.userid = telnetuserid.getText();
        Main.pass = telnetpasswd.getText();

        this.setVisible(false);
    }//GEN-LAST:event_telnetConnectbuttonActionPerformed

    private void telnetQuitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telnetQuitbuttonActionPerformed
        // TODO add your handling code here:
        Main.TX_Text += "~QUIT\n";
        myarq.Message("Disconnecting from telnet", 5);
         this.setVisible(false);
    }//GEN-LAST:event_telnetQuitbuttonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                telnetJDialog dialog = new telnetJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton telnetCancelbutton;
    private javax.swing.JButton telnetConnectbutton;
    private javax.swing.JButton telnetOKbutton;
    private javax.swing.JButton telnetQuitbutton;
    private javax.swing.JTextField telnethost;
    private javax.swing.JTextField telnetpasswd;
    private javax.swing.JTextField telnetport;
    private javax.swing.JTextField telnetuserid;
    // End of variables declaration//GEN-END:variables

}
